AlgebraWebshop/Areas/Admin/Controllers/ProductCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AlgebraWebshop.Data;
using AlgebraWebshop.Models;
using Microsoft.AspNetCore.Authorization;

namespace AlgebraWebshop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductCategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductCategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/ProductCategories
        public async Task<IActionResult> Index(int productId)
        {
            if (productId <= 0)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(productId);
            if (product == null)
            {
                return NotFound();
            }
            List<ProductCategory> list = await (
                    from pc in _context.ProductCategory
                    where pc.ProductId == productId
                    select new ProductCategory()
                    {
                        Id = pc.Id,
                        ProductId = pc.ProductId,
                        CategoryId = pc.CategoryId,
                        ProductTitle = _context.Product.Where(p => p.Id == pc.ProductId).FirstOrDefault().Title,
                        CategoryTitle = _context.Category.Where(c => c.Id == pc.CategoryId).FirstOrDefault().Title,
                    }).ToListAsync();
            ViewBag.ProductId = productId;

            return View(list);
        }

        // GET: Admin/ProductCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productCategory = await _context.ProductCategory
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productCategory == null)
            {
                return NotFound();
            }

            productCategory.ProductTitle = _context.Product.Where(p => p.Id == productCategory.ProductId).First().Title;
            productCategory.CategoryTitle = _context.Category.Where(c => c.Id == productCategory.ProductId).First().Title;

            return View(productCategory);
        }

        // GET: Admin/ProductCategories/Create
        public IActionResult Create(int productId)
        {
            if (productId <= 0)
            {
                return NotFound();
            }

            var product = _context.Product.Find(productId);
            if (product == null)
            {
                return NotFound();
            }

            ViewBag.ProductId = productId;
            var cat = new SelectList(_context.Category, "Id", "Title");
            //TODO: remove already set categories
            ViewBag.Categories = cat;
            ProductCategory pc = new ProductCategory() { 
                ProductId = productId,
                ProductTitle = product.Title
            };

            return View(pc);
        }

        // POST: Admin/ProductCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProductId,CategoryId")] ProductCategory productCategory)
        {
            ModelState.Remove("ProductTitle");
            ModelState.Remove("CategoryTitle");
            if (ModelState.IsValid)
            {
                _context.Add(productCategory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { productId = productCategory.ProductId });
            }
            return View(productCategory);
        }

        // GET: Admin/ProductCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productCategory = await _context.ProductCategory.FindAsync(id);
            if (productCategory == null)
            {
                return NotFound();
            }

            var cat = new SelectList(_context.Category, "Id", "Title", productCategory.CategoryId);
            //TODO: remove already set categories
            ViewBag.Categories = cat;
            productCategory.ProductTitle = _context.Product.Where(p => p.Id == productCategory.ProductId).First().Title;

            return View(productCategory);
        }

        // POST: Admin/ProductCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProductId,CategoryId")] ProductCategory productCategory)
        {
            if (id != productCategory.Id)
            {
                return NotFound();
            }

            ModelState.Remove("ProductTitle");
            ModelState.Remove("CategoryTitle");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productCategory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductCategoryExists(productCategory.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { productId = productCategory.ProductId });
            }
            return View(productCategory);
        }

        // GET: Admin/ProductCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productCategory = await _context.ProductCategory
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productCategory == null)
            {
                return NotFound();
            }

            productCategory.ProductTitle = _context.Product.Where(p => p.Id == productCategory.ProductId).First().Title;
            productCategory.CategoryTitle = _context.Category.Where(c => c.Id == productCategory.ProductId).First().Title;

            return View(productCategory);
        }

        // POST: Admin/ProductCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productCategory = await _context.ProductCategory.FindAsync(id);
            int productId = 0;
            if (productCategory != null)
            {
                productId = productCategory.ProductId;
                _context.ProductCategory.Remove(productCategory);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { productId = productId });
        }

        private bool ProductCategoryExists(int id)
        {
            return _context.ProductCategory.Any(e => e.Id == id);
        }
    }
}

AlgebraWebshop/Areas/Admin/Controllers/ProductImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AlgebraWebshop.Data;
using AlgebraWebshop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.CodeAnalysis;

namespace AlgebraWebshop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductImagesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductImagesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/ProductImages
        public async Task<IActionResult> Index(int productId)
        {
            if (productId <= 0)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(productId);
            if (product == null)
            {
                return NotFound();
            }

            var images = await _context.ProductImage.Where(i => i.ProductId == productId).ToListAsync();
            ViewBag.product = product;

            return View(images);
        }

        // GET: Admin/ProductImages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productImage = await _context.ProductImage
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productImage == null)
            {
                return NotFound();
            }

            return View(productImage);
        }

        // GET: Admin/ProductImages/Create
        public IActionResult Create(int productId)
        {
            if (productId <= 0)
            {
                return NotFound();
            }

            var product = _context.Product.Find(productId);
            if (product == null)
            {
                return NotFound();
            }
            ViewBag.product = product;
            ProductImage pi = new ProductImage()
            {
                ProductId = productId
            };

            return View(pi);
        }

        // POST: Admin/ProductImages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProductId,ImageUrl,Name,Description,MainImage")] ProductImage productImage, IFormFile UploadImage)
        {
            if (UploadImage == null)
            {
                ModelState.AddModelError("ImageUrl", "Image is mandatory!");
            }
            
            var fileextension = System.IO.Path.GetExtension(UploadImage.FileName);
            if (fileextension != ".jpg" && fileextension != ".jpeg" && fileextension != ".png")
            {
                ModelState.AddModelError("ImageUrl", "Only jpg, jpeg and png files are allowed!");
            }
            if (ModelState.IsValid)
            {
                // Save image to wwwroot/images
                var filename = Guid.NewGuid().ToString() + fileextension;
                var path = System.IO.Path.Combine(System.IO.Directory.GetCurrentDirectory(), "wwwroot/images", filename);
                using (var stream = new System.IO.FileStream(path, System.IO.FileMode.Create))
                {
                    await UploadImage.CopyToAsync(stream);
                }
                // primjer rezultata: J:\Programiranje\.NET\AlgebraWebshop\AlgebraWebshop\wwwroot\images\123456.jpg spremanja datoteke
                // format koji nam treba za imageUrl /images/123456.jpg
                productImage.ImageUrl = "/images/" + filename;

                _context.Add(productImage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { productId = productImage.ProductId });
            }

            var product = _context.Product.Find(productImage.ProductId);
            if (product == null)
            {
                return NotFound();
            }
            ViewBag.product = product;

            return View(productImage);
        }

        // GET: Admin/ProductImages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productImage = await _context.ProductImage.FindAsync(id);
            if (productImage == null)
            {
                return NotFound();
            }
            return View(productImage);
        }

        // POST: Admin/ProductImages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProductId,ImageUrl,Name,Description,MainImage")] ProductImage productImage, IFormFile UploadImage)
        {
            if (id != productImage.Id)
            {
                return NotFound();
            }

            ModelState.Remove("UploadImage");
            if (ModelState.IsValid)
            {
                try
                {
                    string oldFile = "";
                    // check if new image is uploaded, if so, replace the old one
                    if (UploadImage != null)
                    {
                        // save to disk
                        var fileextension = System.IO.Path.GetExtension(UploadImage.FileName);
                        // Save image to wwwroot/images
                        var filename = Guid.NewGuid().ToString() + fileextension;
                        var path = System.IO.Path.Combine(System.IO.Directory.GetCurrentDirectory(), "wwwroot/images", filename);
                        using (var stream = new System.IO.FileStream(path, System.IO.FileMode.Create))
                        {
                            await UploadImage.CopyToAsync(stream);
                        }
                        oldFile = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", productImage.ImageUrl.Replace("/images/", ""));
                        productImage.ImageUrl = "/images/" + filename;
                    }

                    _context.Update(productImage);
                    await _context.SaveChangesAsync();

                    if (oldFile != "")
                    {
                        if (System.IO.File.Exists(oldFile))
                        {
                            System.IO.File.Delete(oldFile);
                        }
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductImageExists(productImage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { productId = productImage.ProductId });
            }
            return View(productImage);
        }

        // GET: Admin/ProductImages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productImage = await _context.ProductImage
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productImage == null)
            {
                return NotFound();
            }

            return View(productImage);
        }

        // POST: Admin/ProductImages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productImage = await _context.ProductImage.FindAsync(id);
            int productId = 0;
            if (productImage != null)
            {
                productId = productImage.ProductId;
                var filename = productImage.ImageUrl.Replace("/images/", "");
                var path = System.IO.Path.Combine(System.IO.Directory.GetCurrentDirectory(), "wwwroot/images", filename);               
                _context.ProductImage.Remove(productImage);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { productId = productId });
        }

        private bool ProductImageExists(int id)
        {
            return _context.ProductImage.Any(e => e.Id == id);
        }
    }
}

AlgebraWebshop/Areas/Admin/Views/Products/Create.cshtml
@model AlgebraWebshop.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Unit" class="control-label"></label>
                <input asp-for="Unit" class="form-control" />
                <span asp-validation-for="Unit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" type="number" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" type="number" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" type="number" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VAT" class="control-label"></label>
                <input asp-for="VAT" type="number" class="form-control" />
                <span asp-validation-for="VAT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlgebraWebshop/Areas/Admin/Views/Products/Delete.cshtml
@model AlgebraWebshop.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VAT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VAT)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AlgebraWebshop/Areas/Admin/Views/Products/Details.cshtml
@model AlgebraWebshop.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VAT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VAT)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AlgebraWebshop/Areas/Admin/Views/Products/Edit.cshtml
@model AlgebraWebshop.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Unit" class="control-label"></label>
                <input asp-for="Unit" class="form-control" />
                <span asp-validation-for="Unit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" type="number" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" type="number" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" type="number" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VAT" class="control-label"></label>
                <input asp-for="VAT" type="number" class="form-control" />
                <span asp-validation-for="VAT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlgebraWebshop/Areas/Admin/Views/Products/Index.cshtml
@model IEnumerable<AlgebraWebshop.Models.Product>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                Image
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Unit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Discount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VAT)
            </th>
            <th>
                Total price per unit
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                    @if (item.ProductImages == null || item.ProductImages.Count < 1)
                    {
                        <img width="100" src="~/images/no-image.jpg" alt="no image" />
                    }
                    else
                    {
                        var mainImg = item.ProductImages.Where(i => i.MainImage == true).FirstOrDefault();
                        if (mainImg != null)
                        {
                            <img width="100" src="@mainImg.ImageUrl" alt="@mainImg.Name" />
                        }
                        else
                        {
                            <img width="100" src="@item.ProductImages.First().ImageUrl" alt="@item.ProductImages.First().Name" />
                        }
                    }
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Unit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                 @Html.DisplayFor(modelItem => item.Price) €
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Discount) %
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VAT) %
            </td>
            <td>
                    @item.TotalPrice().ToString("0.00") €
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                <a asp-controller="ProductCategories" asp-action="Index" asp-route-productId="@item.Id">Categories</a> |
                <a asp-controller="ProductImages" asp-action="Index" asp-route-productId="@item.Id">Images</a>
            </td>
        </tr>
}
    </tbody>
</table>